POST http://localhost:3000/orders
Content-Type: application/json

{
  "products": [
    {
      "product": "65ddd5995bacc608d6363cc0",
      "selectedOptions": []
    }
  ],
  "table": 1
}

###

POST http://localhost:3000/orders  
Content-Type: application/json

{
  "products": [
    {
      "product": "65ddd5995bacc608d6363cc4",
      "selectedOptions": []
    },
    {
      "product": "65ddd5995bacc608d6363cc8", 
      "selectedOptions": []
    }
  ],
  "table": 2
}

### 

POST http://localhost:3000/orders
Content-Type: application/json

{
  "products": [
    {
      "product": "65ddd5995bacc608d6363ccc",
      "selectedOptions": []
    },
    {
      "product": "65ddd5995bacc608d6363cd0",
      "selectedOptions": []
    }
  ],
  "table": 3  
}

###

POST http://localhost:3000/orders
Content-Type: application/json  

{
  "products": [
    {
      "product": "65ddd5995bacc608d6363cd8",
      "selectedOptions": []
    },
    {
      "product": "65ddd5995bacc608d6363cd0",
      "selectedOptions": []
    },
    {
      "product": "65ddd5995bacc608d6363cd4",
      "selectedOptions": []
    }
  ],
  "table": 4
}
###

POST http://localhost:3000/orders
Content-Type: application/json  

{
  "products": [
    {
      "product": "65ddd5995bacc608d6363cd0",
      "selectedOptions": []
    },
    {
      "product": "65ddd5995bacc608d6363cd4",
      "selectedOptions": []
    }
  ],
  "table": 51
}
