### Get all orders
GET https://nl-app.onrender.com/orders
role: employee

### Get unpaid orders
GET http://localhost:3000/orders/unpaid
role: employee

### Get order by ID 
GET http://localhost:3000/orders/65dbad38a99e866200021810

###
// Change status to "processed"
PATCH http://localhost:3000/orders/65dbad38a99e866200021810/processed

###
// Change status to "paid"  
PATCH http://localhost:3000/orders/65dbad38a99e866200021810/paid

###
POST http://localhost:3000/orders
Content-Type: application/json

{
  "products": [
    {
      "product": "65d7d82714056c7ab1b24562"
    }
  ],
  "table": 5
}
