### Create new reservation
POST http://localhost:3000/reservations
Content-Type: application/json

{
  "name": "Nour",
  "phone": "565-0000",
  "dateTime": "2024-03-15T17:00:00.000Z", 
  "numGuests": 4,
  "notes": "No notes"
}

### Get all reservations
GET http://localhost:3000/reservations
role: employee

### Get reservation by ID 
GET http://localhost:3000/reservations/65d3cd3bc414aa5ac1de8d3c

### Update reservation
PATCH http://localhost:3000/reservations/65d3cd3bc414aa5ac1de8d3c
Content-Type: application/json

{
  "phone": "555-5555",
  "numGuests": 5
}

### Delete reservation
DELETE http://localhost:3000/reservations/65d43456ad47c835b3502b02
