### Create new product
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "banana Smoothie",
  "price": 3.50,
  "ingredients": "Mango, ice, mango nectar, sugar",
  "category": "drink",
  "options": [
    {
      "name": "Add protein",
      "price": 1.00
    }
  ],
  "stockable": true,
  "qty": 30
}

### Get all products
GET http://localhost:3000/products
role: employee

###
GET http://localhost:3000/products/categories/food

### Get reservation by ID 
GET http://localhost:3000/products/65d4720710a0f7f51bc7a179

### Update product
PATCH http://localhost:3000/products/65d7d82714056c7ab1b24582
Content-Type: application/json

{
  "qty": 1000
}

### Delete reservation
DELETE http://localhost:3000/products/65e1178897a6e20305e9fed4